### ISSUE TITLE
Help for the test results

### ISSUE THREAD

**Issue by zhyyfaan** [qinghew/SDGAN#1]
Could you please share the test results of your own method and other methods compared on the "photo to sketch" task in this paper ?

**Comment by qinghew** [comment]
The compared results can be found in this [page](https://www.sciengine.com/SSI/article?doi=10.1360/SSI-2021-0321&scroll=).

**Comment by zhyyfaan** [comment]
Thanks for your reply, but I still can't find the way to get the results, I can't even find where the results are in this link.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinghew/SDGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 中午1:26
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinghew/SDGAN] Help for the test results (Issue #1)





 
The compared results can be found in this page.

**Comment by qinghew** [comment]
If you want the quantitative comparison results, please download PDF from [page](https://www.sciengine.com/SSI/article?doi=10.1360/SSI-2021-0321&scroll=).
If you want the generation results of ours and baselines, you should run the codes to get.

**Comment by zhyyfaan** [comment]
Thanks ~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinghew/SDGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinghew/SDGAN] Help for the test results (Issue #1)





 
If you want the quantitative comparison results, please download PDF from page.
 If you want the generation results of ours and baselines, you should run the codes to get.

**Comment by zhyyfaan** [comment]
I'm sorry to bother you again, but I want to know if you can share the pretrained model so that I can test directly.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinghew/SDGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月9日(星期六) 下午3:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinghew/SDGAN] Help for the test results (Issue #1)





 
Closed #1.

**Comment by qinghew** [comment]
For business reasons, we do not provide the pretrained models. The provided codes are sufficient to reproduce.

**Comment by zhyyfaan** [comment]
Ok，thanks for your reply


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "qinghew/SDGAN"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上7:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [qinghew/SDGAN] Help for the test results (Issue #1)





 
For business reasons, we do not provide the pretrained models. The provided codes are sufficient to reproduce.
