### ISSUE TITLE
有关训练与测试的问题

### ISSUE THREAD

**Issue by Pradur241** [qinghew/SDGAN#2]
您好！我下载了CUFS数据集并将其分为了trainA\B与testA\B。但是在测试的时候，模型运行起来提示这个报错是什么原因呢？

```
RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
        Missing key(s) in state_dict: "resblocks.0.conv_block.6.weight", "resblocks.0.conv_block.6.bias", "resblocks.1.conv_block.6.weight", "resblocks.1.conv_block.6.bias", "resblocks.2.conv_block.6.weight", "resblocks.2.conv_block.6.bias", "resblocks.3.conv_block.6.weight", "resblocks.3.conv_block.6.bias", "resblocks.4.conv_block.6.weight", "resblocks.4.conv_block.6.bias", "resblocks.5.conv_block.6.weight", "resblocks.5.conv_block.6.bias", "resblocks.6.conv_block.6.weight", "resblocks.6.conv_block.6.bias", "resblocks.7.conv_block.6.weight", "resblocks.7.conv_block.6.bias", "resblocks.8.conv_block.6.weight", "resblocks.8.conv_block.6.bias". 
        Unexpected key(s) in state_dict: "resblocks.0.conv_block.5.weight", "resblocks.0.conv_block.5.bias", "resblocks.1.conv_block.5.weight", "resblocks.1.conv_block.5.bias", "resblocks.2.conv_block.5.weight", "resblocks.2.conv_block.5.bias", "resblocks.3.conv_block.5.weight", "resblocks.3.conv_block.5.bias", "resblocks.4.conv_block.5.weight", "resblocks.4.conv_block.5.bias", "resblocks.5.conv_block.5.weight", "resblocks.5.conv_block.5.bias", "resblocks.6.conv_block.5.weight", "resblocks.6.conv_block.5.bias", "resblocks.7.conv_block.5.weight", "resblocks.7.conv_block.5.bias", "resblocks.8.conv_block.5.weight", "resblocks.8.conv_block.5.bias". 
```

**Comment by qinghew** [comment]
> 您好！我下载了CUFS数据集并将其分为了trainA\B与testA\B。但是在测试的时候，模型运行起来提示这个报错是什么原因呢？
> 
> ```
> RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
>         Missing key(s) in state_dict: "resblocks.0.conv_block.6.weight", "resblocks.0.conv_block.6.bias", "resblocks.1.conv_block.6.weight", "resblocks.1.conv_block.6.bias", "resblocks.2.conv_block.6.weight", "resblocks.2.conv_block.6.bias", "resblocks.3.conv_block.6.weight", "resblocks.3.conv_block.6.bias", "resblocks.4.conv_block.6.weight", "resblocks.4.conv_block.6.bias", "resblocks.5.conv_block.6.weight", "resblocks.5.conv_block.6.bias", "resblocks.6.conv_block.6.weight", "resblocks.6.conv_block.6.bias", "resblocks.7.conv_block.6.weight", "resblocks.7.conv_block.6.bias", "resblocks.8.conv_block.6.weight", "resblocks.8.conv_block.6.bias". 
>         Unexpected key(s) in state_dict: "resblocks.0.conv_block.5.weight", "resblocks.0.conv_block.5.bias", "resblocks.1.conv_block.5.weight", "resblocks.1.conv_block.5.bias", "resblocks.2.conv_block.5.weight", "resblocks.2.conv_block.5.bias", "resblocks.3.conv_block.5.weight", "resblocks.3.conv_block.5.bias", "resblocks.4.conv_block.5.weight", "resblocks.4.conv_block.5.bias", "resblocks.5.conv_block.5.weight", "resblocks.5.conv_block.5.bias", "resblocks.6.conv_block.5.weight", "resblocks.6.conv_block.5.bias", "resblocks.7.conv_block.5.weight", "resblocks.7.conv_block.5.bias", "resblocks.8.conv_block.5.weight", "resblocks.8.conv_block.5.bias". 
> ```

你好，你训练模型了吗？看起来是模型没有加载成功。如果你已经训练好了模型并且提供了正确的加载路径还出现这个错误的话，可能是你训练和测试时选择的模型结构不一样，我记得有个选unet还是resnet的设定

**Comment by Pradur241** [comment]
> > 您好！我下载了CUFS数据集并将其分为了trainA\B与testA\B。但是在测试的时候，模型运行起来提示这个报错是什么原因呢？
> > ```
> > RuntimeError: Error(s) in loading state_dict for ResnetGenerator:
> >         Missing key(s) in state_dict: "resblocks.0.conv_block.6.weight", "resblocks.0.conv_block.6.bias", "resblocks.1.conv_block.6.weight", "resblocks.1.conv_block.6.bias", "resblocks.2.conv_block.6.weight", "resblocks.2.conv_block.6.bias", "resblocks.3.conv_block.6.weight", "resblocks.3.conv_block.6.bias", "resblocks.4.conv_block.6.weight", "resblocks.4.conv_block.6.bias", "resblocks.5.conv_block.6.weight", "resblocks.5.conv_block.6.bias", "resblocks.6.conv_block.6.weight", "resblocks.6.conv_block.6.bias", "resblocks.7.conv_block.6.weight", "resblocks.7.conv_block.6.bias", "resblocks.8.conv_block.6.weight", "resblocks.8.conv_block.6.bias". 
> >         Unexpected key(s) in state_dict: "resblocks.0.conv_block.5.weight", "resblocks.0.conv_block.5.bias", "resblocks.1.conv_block.5.weight", "resblocks.1.conv_block.5.bias", "resblocks.2.conv_block.5.weight", "resblocks.2.conv_block.5.bias", "resblocks.3.conv_block.5.weight", "resblocks.3.conv_block.5.bias", "resblocks.4.conv_block.5.weight", "resblocks.4.conv_block.5.bias", "resblocks.5.conv_block.5.weight", "resblocks.5.conv_block.5.bias", "resblocks.6.conv_block.5.weight", "resblocks.6.conv_block.5.bias", "resblocks.7.conv_block.5.weight", "resblocks.7.conv_block.5.bias", "resblocks.8.conv_block.5.weight", "resblocks.8.conv_block.5.bias". 
> > ```
> 
> 你好，你训练模型了吗？看起来是模型没有加载成功。如果你已经训练好了模型并且提供了正确的加载路径还出现这个错误的话，可能是你训练和测试时选择的模型结构不一样，我记得有个选unet还是resnet的设定

你好，我训练过模型了，并且在测试的时候手动修改lates_net_G_A2B.pth为lates_net_G.pth。测试集用的testA，主要构成是CUFS的一百张sketch图片。我看了看cyclegan的issue，提示我通过添加--no_dropout能解决这个问题。

但是目前又出现了一个新的问题。运行完test.py后，results的a和b文件夹内都没有结果。您遇到过这个问题吗？如果可以，能添加微信或qq详聊吗？我的qq1042533208

**Comment by qinghew** [comment]
好的，加你了
